### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by DevataDev** [rlaphoenix/pywidevine#1]
Is the Provisioned CDM Path, using same style with others ? 

Thank you

**Comment by rlaphoenix** [comment]
You create a Device object, e.g., by doing `Device.load(r"C:/Path/To/a/device.wvd")`, this is then passed to the CDM.

The .wvd file can be created from an RSA PEM private key file and Client ID Blob by manually creating the Device object and then using the `dump()` method.

```py
# e.g., for an Android L3:
from pathlib import Path

device = Device(
    type_=Device.Types.ANDROID,
    security_level=3,
    flags=None,
    private_key=Path(r"C:/Path/To/a/Private-Key-PEM-or-DER-file").read_bytes(),
    client_id=Path(r"C:/Path/To/a/Client-ID-Blob-file").read_bytes()
)
# save it to a .wvd file for easier loading next time
device.dump(r"C:/Where/To/save/the/device.wvd")
```

**Note**: If you have a VMP blob (a FileHashes blob) and it's not added to the Client ID blob, then the .wvd file will effectively have no VMP or File Hashes verification. The FileHashes is expected to be inside the Client ID blob to reduce possible duplication.

**Comment by DevataDev** [comment]
Thank you for the explanation Sir. Really appreciate it 😄

**Comment by rlaphoenix** [comment]
I've added a new `create-device` command to the CLI which you can use to convert to the .wvd format a bit easier: See https://github.com/rlaphoenix/pywidevine/commit/5e93d6321d7ba6dcc0fc512e2dca9c94a233bf34

**Comment by DevataDev** [comment]
> I've added a new `create-device` command to the CLI which you can use to convert to the .wvd format a bit easier: See [5e93d63](https://github.com/rlaphoenix/pywidevine/commit/5e93d6321d7ba6dcc0fc512e2dca9c94a233bf34)

Thank you really appreciate it 👍  and thank you for this awesome tools :)
