### ISSUE TITLE
Question: How to generate a token for requesting a license?

### ISSUE THREAD

**Issue by OevreFlataeker** [rlaphoenix/pywidevine#14]
I want to contact a license url which requires a client token before issuing a license.
It seems the overall process is very similar to what is described here: https://pallycon.com/docs/en/multidrm/license/license-token/
When analyzing the data flow between the client and the streaming site I can nowhere see this token request-response.

Is this something which is done by the CDM when initializing? 
As far as I understand the file "license_protocol.proto" contains definition for those security policy fields like if HDCP is required etc. 

How can I a) decode a token I see in the browsers devtools to see what's in there and b) generate my own?

**Comment by rlaphoenix** [comment]
Hi, this question is out of the scope of the project. This would be service-specific, not done by the project itself.

**Comment by OevreFlataeker** [comment]
Thanks, I was able to solve it this morning!
