### ISSUE TITLE
Can't dump wvd if didn't pass --vmp argument

### ISSUE THREAD

**Issue by DevataDev** [rlaphoenix/pywidevine#2]
Hi @rlaphoenix ,
Sorry for bothering again, Is the VMP a required parameter ?
Can't do the wvd generation if we didn't pass the VMP arguments.

Is it related with this required=True code ? (https://github.com/rlaphoenix/pywidevine/blob/e1951d20d0e03bcb5698fa8c4f72a5d880617caf/pywidevine/main.py#L168)

Thank you

**Comment by rlaphoenix** [comment]
Nice spot, fixed in https://github.com/rlaphoenix/pywidevine/commit/e1532b1451b56a2d639590564c7d2194cafedcdc

It will be in the next release which will be somewhat soon hopefully.
