### ISSUE TITLE
Various queries.

### ISSUE THREAD

**Issue by DumberSoft** [rlaphoenix/pywidevine#31]
Hello greetings I have several questions I hope I can solve them by this means.

- How is it used?
- I have two files that are blob ID and blob key how can I make it work?
- How can I configure the files and make it work?
- It works with L1 will also be compatible?

**Comment by rlaphoenix** [comment]
Hi,

1. There is various information in the README regarding Usage, https://github.com/rlaphoenix/pywidevine#usage
2. Run `pywidevine create-device --help` to convert typical Client ID blob files and PEM or DER private key files to a singular Widevine Device file (`.wvd`). This is the file you will use hence forth with Pywidevine either directly via CLI or other scripts/tools that use Pywidevine.
3. You will have to explain further what you want configured. Generally, there isn't anything you need to configure with pywidevine itself.
4. Yes, any device key is supported, as long as it's an RSA-2048 key, which basically all are except some newer Chrome CDM ones.

**Comment by DumberSoft** [comment]
If for Chrome cdm but in L1 I want to use it, will you have a Skype or telegram to contact me and you can help me please.

**Comment by rlaphoenix** [comment]
You are only meant to use Device Keys you have yourself, test keys, or keys you have explicit rights to use. I cannot help further on this matter.

**Comment by DumberSoft** [comment]
But what I mean is that I already have the .wvd but I would just like to know where I connect it or through where, since I have seen in other forums but there is no detailed explanation, therefore I would like to know about it, once I I have the .wvd now where do I connect it or what else do I download, help only on this question please.

**Comment by rlaphoenix** [comment]
As I said there's examples on using WVD files via pywidevine in the README under Usage section.
