### ISSUE TITLE
Cant parse license url

### ISSUE THREAD

**Issue by fremzuck** [rlaphoenix/pywidevine#37]
I have error but requests response is work but cant find key

pywidevine\cdm.py", line 393, in parse_license
    raise InvalidLicenseMessage(f"Could not parse license_message as a SignedMessage, {e}")
pywidevine.exceptions.InvalidLicenseMessage: Could not parse license_message as a SignedMessage, Error parsing message

```
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0',
    'Accept': '*/*',
    'Accept-Language': 'en',
    # 'Accept-Encoding': 'gzip, deflate, br',
    'Content-Type': 'application/json',
    'Referer': 'https://astrogo.astro.com.my/',
    'cache-control': 'no-cache , no-store',
    'Origin': 'https://astrogo.astro.com.my',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-site',
    'authorization': 'Bearer eyJraWQiOiI2OWM2MzRkMi0zNjBiLTQ0YzEtODUwZC05',
    'Connection': 'keep-alive',
}

json_data = {
    'contentID': '601',
    'contentType': 2,
    'authorizationToken': 'AAAAQAAAAKEAAAB',
    'authorizationTokenType': '1',
    'licenseChallenge': 'CAES7SsSIwohCgsiAzYwMUjj3JWl0Hfy5q6ho/eyujdwdo6nYgGsbLgpkoUAAAAAQAAABQABQAQ3hym9dgCxVs=',
    'playbackSessionCookie': None,
}
```

**Comment by rlaphoenix** [comment]
How are you passing the `licenseChallenge` back to pywidevine? It sounds like you're making the same mistake as #25

**Comment by fremzuck** [comment]
> How are you passing the license from the response back to pywidevine? It sounds like you're making the same mistake as #25

I remove data=challenge because license return 401 then remove license return 200

I dont know how to add license challenge payload to script can you guide me ?

**Comment by rlaphoenix** [comment]
I do not provide support with making license calls to specific services. I can only support issues or questions related to pywidevine itself. As I said look into how you are passing back the 200 OK response back to pywidevine (the `parse_license` call). You are likely passing back the full response as bytes or text to `parse_license` when in reality you may need to JSON-parse the response first, then pass `parse_license` a specific item from the JSON response. Again, see #25 as someone else has had this similar issue already.

**Comment by fremzuck** [comment]
> I do not provide support with making license calls to specific services. I can only support issues or questions related to pywidevine itself. As I said look into how you are passing back the 200 OK response back to pywidevine (the `parse_license` call). You are likely passing back the full response as bytes or text to `parse_license` when in reality you may need to JSON-parse the response first, then pass `parse_license` a specific item from the JSON response. Again, see #25 as someone else has had this similar issue already.

yes i try remove data=challenge license return work and i replace license.content with licence.json()['licenseData'][0]
but error
File "C:\Users\user\Downloads\Compressed\pywidevine-master\getkey.py", line 60, in <module>
    cdm.parse_license(session_id, licence.json()['licenseData'][0])
  File "C:\Users\user\Downloads\Compressed\pywidevine-master\pywidevine\cdm.py", line 410, in parse_license
    raise InvalidContext("Cannot parse a license message without first making a license request")
pywidevine.exceptions.InvalidContext: Cannot parse a license message without first making a license request

my code is

```
licence = requests.post("https://sg-sg-sg/license", headers=headers, proxies=proxies, json=json_data)
""" licence.raise_for_status() """

print(licence.json()['licenseData'][0])


# parse license challenge
cdm.parse_license(session_id, licence.json()['licenseData'][0])
```

**Comment by fremzuck** [comment]
licence.json()['licenseData'][0] return

CAISigIKNAoQPj+5j01murZCHaAmWrwLXRIQPj+5j01murZCHaAmWrwLXRoAIAEoADgAQABI+dzbqQYSFAgBEAAYACDs6k0o7OpNMOzqTWAAGlYSEAHcXJeHoy0sKJABARkUYF4aQHyMzI21kjdtxyZLWbZu2TplCdJo+a3GFZcSbeXXLDeeM38BDjd07Wwl7RWXBbmKhd1AO91PV+x5KLanBD1+wVQgARpWChD3Satx8ieZm/sJj3M1mqwQEhBlOFDtUhyqCdT8+4YoN38wGhAZqo8Ruv/Za6OPcy+JKaB9IAIoATIECAAQKkISChBrYzE2ABN1bLOLLxugAAAIYgAg+dzbqQY449yVmwZQAhoguOXpwVppmarfdwRUs9hGSf6GbRbKLJiez0k0v9yl4UoigAFAUo33TiYCB+tvuPj9acWytORKH2RsLrePfmSecwej2h7T0VAi2yMgIYiOtcE5rvqdseTVmdx7qxMV79SFNcts4Y9dTY3lVudJWi2eUuEL30IOiuoOULSTliMM65ixOUZiO/A9hgcCrxTWSGjrAXcFNC1acsnZHxWgOF3py2n8EjozCjExOC4xLjIgQnVpbHQgb24gQXVnIDE2IDIwMjMgMTI6NTU6MDAgKDE2OTIyMTU2ODYpQAFKsAEAAAACAAAAsAAFABCziy8bGvEz1QAAAFAAAAAQAAAAYgAAAEAAAATdWwAAAAAABN1bAAAAAAAAAAAAAAAAQAAAKgAAAAQAAAAugAAABAAAADMAAAAEAAAAAAAAAAAAAAA6gAAABCVqpAvPkZ9yVW/PxhQ6+esuVyjxHeHCr2i7kzPwHmSMlgB

if i add data=challenge in requests license return http code 400

**Comment by rlaphoenix** [comment]
> pywidevine.exceptions.InvalidContext: Cannot parse a license message without first making a license request

Notice this error. That means whatever challenge you sent with the request was either no challenge, or an old challenge not made by that instance of pywidevine. The challenge must be made by the same pywidevine instance that you are using `parse_license` with.

> if i add data=challenge in requests license return http code 400

Well, maybe it doesn't accept a challenge like that. Maybe it must be sent in a JSON object instead of as raw bytes. Do remember that `get_license_challenge` returns the challenge as bytes. It's also possible you need to send it as Base64 instead.

**Comment by fremzuck** [comment]
> > pywidevine.exceptions.InvalidContext: Cannot parse a license message without first making a license request
> 
> Notice this error. That means whatever challenge you sent with the request was either no challenge, or an old challenge not made by that instance of pywidevine. The challenge must be made by the same pywidevine instance that you are using `parse_license` with.
> 
> > if i add data=challenge in requests license return http code 400
> 
> Well, maybe it doesn't accept a challenge like that. Maybe it must be sent in a JSON object instead of as raw bytes. Do remember that `get_license_challenge` returns the challenge as bytes. It's also possible you need to send it as Base64 instead.

Can you help me? What value do I need to pass to the function? get_license_challenge

**Comment by rlaphoenix** [comment]
At this point you are having me do all the work when documentation and examples are already available. Please just take a look at the README's example, and documentation. For more direct information look at the doc-strings of the functions. E.g., https://github.com/rlaphoenix/pywidevine/blob/c71f867a72e16c7cec1fb97268ee433208865f60/pywidevine/cdm.py#L269C12-L289
