### ISSUE TITLE
How to pass header?

### ISSUE THREAD

**Issue by amjiddader** [rlaphoenix/pywidevine#38]
Hi, 

I need to pass user-agent in request header 
I tried to create a header.py and added user-agent: Mozilla... as header in header.py 

and then import header but its not working... 

Does someone know how to pass user-agent? in header request? 

```
send license challenge (assuming a generic license server SDK with no API front)
licence = requests.post("https://...", data=challenge)
licence.raise_for_status()
```

**Comment by rlaphoenix** [comment]
You are asking how to use the [requests](https://requests.readthedocs.io/en/latest/) library, please read their documentation. This question is unrelated to pywidevine.
