### ISSUE TITLE
Auto select device in whitelist?

### ISSUE THREAD

**Issue by sst311212** [rlaphoenix/pywidevine#4]
It would be great if remote cdm can select random device in user's whitelist automatically.
Thus, users no need to provide specific device in api request if they have multiple device key.

**Comment by rlaphoenix** [comment]
The selection of a random device could be problematic in relation to licensing server robustness though. So I don't know if that's the best idea.

**Comment by DevataDev** [comment]
Yes i am agree with @rlaphoenix it's a bit hard to keep the session if we give random device.

**Comment by rlaphoenix** [comment]
I don't think I will implement this as I do not personally see the need. If you want to randomly choose a device you can always do this on the client side where you list out what devices the user has, then randomly choose one from the list yourself.
